ARDUINO_DIR = /home/jo/usr/arduino-nightly
BOARD_TAG    = jnmicro
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = OneWire JeeLib
AVR_TOOLS_DIR = /usr
ALTERNATE_CORE = jeelabs/avr
include /home/jo/usr/arduino-nightly/Arduino.mk
